{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "picker",
    "version": "2024110401",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "UICoreDemo.UICore",
          "module": "camera",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "picker-2024110401.aar",
          "url": "picker-2024110401.aar",
          "size": 353131,
          "sha512": "477808831fb6daf6b4f8aac07ad14b109274b4957c540adb08fa3704768c6b3ce945e9061d6607e5250ffa2cf982dc217e79ea4420a916ef9a6798134f345beb",
          "sha256": "cd67a763b22c36acbd511717b3794a1b8c88ce73807578c59040ec9c9e0c5906",
          "sha1": "b7b1c0bd781af8c12d6998bbdac87d43b70fbc6c",
          "md5": "33659f7d1c8044254ecb428beb10fc69"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.angcyo",
          "module": "record",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.angcyo",
          "module": "viewmodel",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "UICoreDemo.UICore",
          "module": "camera",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.angcyo",
          "module": "pager",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "picker-2024110401.aar",
          "url": "picker-2024110401.aar",
          "size": 353131,
          "sha512": "477808831fb6daf6b4f8aac07ad14b109274b4957c540adb08fa3704768c6b3ce945e9061d6607e5250ffa2cf982dc217e79ea4420a916ef9a6798134f345beb",
          "sha256": "cd67a763b22c36acbd511717b3794a1b8c88ce73807578c59040ec9c9e0c5906",
          "sha1": "b7b1c0bd781af8c12d6998bbdac87d43b70fbc6c",
          "md5": "33659f7d1c8044254ecb428beb10fc69"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "picker-2024110401-sources.jar",
          "url": "picker-2024110401-sources.jar",
          "size": 81289,
          "sha512": "66474a72eb28a3c50ebffcc2421544f4111aca8b3916ed8d8e4af1e24bf657d38de037aa4b1d02d6f38c9bd6932017e6d60b31e96bcf40eb739caf0ea87ebe0c",
          "sha256": "b3781d461685c1d7dad1b8338c99a5c58053824cabc0557cc803c6aac3685eef",
          "sha1": "e6848e776e5866b4285f5a290804b1163123296a",
          "md5": "973fb1607ab2e18f1378290bcc174495"
        }
      ]
    }
  ]
}
