{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "glide",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113180,
          "sha512": "f2ee30e963d257f0c1eca3067655d7b0a3159fe63f6ab4c35f0e3e4ffe8f010b2d2a41d23a25c99ec8a9d5ea5b73b9b622f22a83453582ee2430512657769032",
          "sha256": "106250ec7110171c809e15bb020083124f8bcd4c28303bd483e7fad5ddf7d15a",
          "sha1": "4b1e907d13396954cc786cee8ad8f14f387a3a0b",
          "md5": "c82a6196afa53f9e303ed5b66055da84"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "widget",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT.aar",
          "url": "glide-hingin-SNAPSHOT.aar",
          "size": 113180,
          "sha512": "f2ee30e963d257f0c1eca3067655d7b0a3159fe63f6ab4c35f0e3e4ffe8f010b2d2a41d23a25c99ec8a9d5ea5b73b9b622f22a83453582ee2430512657769032",
          "sha256": "106250ec7110171c809e15bb020083124f8bcd4c28303bd483e7fad5ddf7d15a",
          "sha1": "4b1e907d13396954cc786cee8ad8f14f387a3a0b",
          "md5": "c82a6196afa53f9e303ed5b66055da84"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "glide-hingin-SNAPSHOT-sources.jar",
          "url": "glide-hingin-SNAPSHOT-sources.jar",
          "size": 35457,
          "sha512": "6ce5bd7301fdc98672fe69ac9435b9a7f2d66ee9dd7f532974f5893b789037d4fdb5295bc0da882721661dca9a8ef4bd21abe2a3177de32eeb29e79ea71206d7",
          "sha256": "ad62f331f298a331f3d826e20887bb98e52a74557a59e2c834bef8d7ddfbe775",
          "sha1": "e89d7f33c7cc1d72ebba76f109bc97e8cad685c6",
          "md5": "046bbd7418977bf57964d044a255c10e"
        }
      ]
    }
  ]
}
