{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "download",
    "version": "hingin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286075,
          "sha512": "8d111f8079f98773488d75bad1e73c6e8bf29ba8efd957b2dea1dc94602a4dc6615b5ece859f31d8370622877400fd2ba9c2436bd3fd943b8ed563e104bcc039",
          "sha256": "ce11d4f806ec9111016679abd8d8ebcc822cb0c1ddb9c5176e164044772a3f0f",
          "sha1": "f319460e4e1285973b8453b593e253852ef13467",
          "md5": "cca871f7fe7a5c72c4d00e21bf9f69bc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "http",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "coroutine",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.angcyo",
          "module": "dslitem",
          "version": {
            "requires": "hingin-SNAPSHOT"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "sqlite",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okhttp",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "okdownload",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.liulishuo.okdownload",
          "module": "ktx",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "download-hingin-SNAPSHOT.aar",
          "url": "download-hingin-SNAPSHOT.aar",
          "size": 286075,
          "sha512": "8d111f8079f98773488d75bad1e73c6e8bf29ba8efd957b2dea1dc94602a4dc6615b5ece859f31d8370622877400fd2ba9c2436bd3fd943b8ed563e104bcc039",
          "sha256": "ce11d4f806ec9111016679abd8d8ebcc822cb0c1ddb9c5176e164044772a3f0f",
          "sha1": "f319460e4e1285973b8453b593e253852ef13467",
          "md5": "cca871f7fe7a5c72c4d00e21bf9f69bc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "download-hingin-SNAPSHOT-sources.jar",
          "url": "download-hingin-SNAPSHOT-sources.jar",
          "size": 42559,
          "sha512": "3a6fe06d0233b4d7e8160c0f00aea28e58b0a37bc4216095b91405228aef4e50236c32c1f2b403af361f9de4354c6311098f7b27d043ec30f63a3cdb48fd8761",
          "sha256": "c0c954bfd6f33897f1da333d43856eec9c3da0e0e5e7bfb7963069b8c398afd8",
          "sha1": "143e9da3c8288cbb073a430eca28bb661fc1e2f7",
          "md5": "b83b7c4dd9d9ef5cbc7d4e49d40dc34f"
        }
      ]
    }
  ]
}
