{
  "formatVersion": "1.1",
  "component": {
    "group": "com.angcyo",
    "module": "widget",
    "version": "2024110401",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "widget-2024110401.aar",
          "url": "widget-2024110401.aar",
          "size": 1909951,
          "sha512": "2561d0fcb63400de722ddb540eac9940cbb7f26d01b0a8fc0fae3e30d46908ba88a87339ade0c2c8c6ec834326d9bc9be6f69a0387059d6fe26cf9ebecb44b11",
          "sha256": "ecee83a3b4d33d759b1dca5e7c198e36dbcf256c6ce2321e845d62f7ca65c08b",
          "sha1": "1a44b47c976d159fada8637d09f67c242a181ed1",
          "md5": "c14cd27c579dc9c6dff55e50ddc0fc93"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.angcyo",
          "module": "library",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "com.angcyo",
          "module": "drawable",
          "version": {
            "requires": "2024110401"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.LaserPeckerIst",
          "module": "AnimatedSvgView",
          "version": {
            "requires": "1.0.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "widget-2024110401.aar",
          "url": "widget-2024110401.aar",
          "size": 1909951,
          "sha512": "2561d0fcb63400de722ddb540eac9940cbb7f26d01b0a8fc0fae3e30d46908ba88a87339ade0c2c8c6ec834326d9bc9be6f69a0387059d6fe26cf9ebecb44b11",
          "sha256": "ecee83a3b4d33d759b1dca5e7c198e36dbcf256c6ce2321e845d62f7ca65c08b",
          "sha1": "1a44b47c976d159fada8637d09f67c242a181ed1",
          "md5": "c14cd27c579dc9c6dff55e50ddc0fc93"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widget-2024110401-sources.jar",
          "url": "widget-2024110401-sources.jar",
          "size": 974323,
          "sha512": "7baba19d29743b9a5f755c7a6ca27c66a8d614c4b09681916be6df3d5bd555470c1038b0a9688640c4dab03ef432f11a4228e5e8552532dfe39185e77bdda81e",
          "sha256": "5e80a1532bfc29325aa8abcea602edf23eeaa18c1057b0110162cb15994853a0",
          "sha1": "6c6b983904871be77f690ddbc2963e598c894367",
          "md5": "26a568f30f26c5c430133e2db8e6fed8"
        }
      ]
    }
  ]
}
